[package]
name = "ros-humble-dual-pose-graph"
version = "1.0.6"

[package.build]
backend = { name = "pixi-build-ros", version = "*" }

[package.build.config]
extra-package-mappings = [
    { g2o = { ros = ["libg2o"] } },
    { as2_core = { conda = ["as2_core"] } },
    { as2_msgs = { conda = ["as2_msgs"] } },
    { libfmt = { conda = ["fmt"] } },
    { ceres = { conda = ["ceres-solver"] } },
    { GeographicLib = { conda = ["geographiclib-cpp"] } },
]
